### PR TITLE
allow new database creation by fixing schema version check logic

### PR DESCRIPTION
**Pull request by nberlee**
fixes https://github.com/GrapheneOS/AttestationServer/issues/135

### CODE REVIEW

**Comment by thestinger** [comment]
This shouldn't happen because of this part:

```
            final SQLiteStatement selectCreated = attestationConn.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name='Configuration'");
            if (!selectCreated.step()) {
                attestationConn.exec("PRAGMA user_version = 6");
            }
            selectCreated.dispose();

**Comment by nberlee** [comment]
Sorry, i am not making this up:
```
Dec 14, 2021 4:02:01 PM com.almworks.sqlite4java.Internal log
INFO: [sqlite] DB[1]: instantiated [samples.db]
Dec 14, 2021 4:02:01 PM com.almworks.sqlite4java.Internal log
INFO: [sqlite] Internal: loaded sqlite4java-linux-amd64-1.0.392 from /app/libsqlite4java-linux-amd64-1.0.392.so
Dec 14, 2021 4:02:01 PM com.almworks.sqlite4java.Internal log
INFO: [sqlite] Internal: loaded sqlite 3.37.0, wrapper 1.3
Dec 14, 2021 4:02:01 PM com.almworks.sqlite4java.Internal log
INFO: [sqlite] DB[1]: opened
Dec 14, 2021 4:02:01 PM app.attestation.server.AttestationServer getUserVersion
INFO: Existing schema version: 1
Dec 14, 2021 4:02:01 PM app.attestation.server.AttestationServer main
INFO: New schema version: 1
Dec 14, 2021 4:02:01 PM app.attestation.server.AttestationServer main
INFO: Vacuum database
Dec 14, 2021 4:02:01 PM com.almworks.sqlite4java.Internal log
INFO: [sqlite] DB[1]: connection closed
Dec 14, 2021 4:02:01 PM com.almworks.sqlite4java.Internal log
INFO: [sqlite] DB[2]: instantiated [attestation.db]
Dec 14, 2021 4:02:01 PM com.almworks.sqlite4java.Internal log
INFO: [sqlite] DB[2]: opened
Dec 14, 2021 4:02:01 PM app.attestation.server.AttestationServer getUserVersion
INFO: Existing schema version: 0
Dec 14, 2021 4:02:01 PM com.almworks.sqlite4java.Internal log
INFO: [sqlite] DB[2]: connection closed
Exception in thread "main" java.lang.RuntimeException: Database schemas older than version 4 are no longer supported. Use an older AttestationServer revision to upgrade.

**Comment by thestinger** [comment]
Did you already create the Configuration table?

**Comment by nberlee** [comment]
Yes.. my docker entrypoint does:
```
sqlite3 attestation.db "CREATE TABLE IF NOT EXISTS Configuration (key TEXT PRIMARY KEY NOT NULL, value NOT NULL)"
sqlite3 attestation.db "INSERT OR REPLACE INTO Configuration VALUES ('emailUsername', '$EMAIL_USERNAME'), ('emailPassword', '$EMAIL_PASSWORD'), ('emailHost', '$EMAIL_HOST'), ('emailPort', '$EMAIL_PORT')"

**Comment by nberlee** [comment]
ah ok, then its an issue specific to me, so close it if you want...

**Comment by thestinger** [comment]
Okay, so that's why it's happening. Also note that the Configuration schema has slightly changed to make it into a `STRICT` table.

**Comment by thestinger** [comment]
I have AttestationServer create the table and then insert the email configuration after the fact. Maybe it would make sense to have a way to make AttestationServer create/update the database and then exit immediately.

**Comment by thestinger** [comment]
The reason AttestationServer has that check is because we originally left user_version at 0 so we can't detect if we just created the database based on user_version being 0 unless we drop support for giving proper error messages with the earliest database version. It's likely that far more than enough time has passed that we could just drop it especially since I doubt many people are self-hosting it.

**Comment by thestinger** [comment]
We only just recently started using user_version for the samples database though.

**Comment by thestinger** [comment]
It would have been smart to immediately set that to 1 at the beginning.

**Comment by thestinger** [comment]
@nberlee If you're doing it that way, you should just run `PRAGMA user_version = 6` yourself. You should also update the Configuration table you're creating to the new schema. I could come up with a better way of setting the initial configuration not requiring modifying the database.

**Comment by thestinger** [comment]
(if you used `PRAGMA user_version = 5` it would update the schema for you)

**Pull request closed without merging**
